spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
  data:
      neo4j:
        uri: bolt://localhost:7687
        username: neo4j
        password: 1234

#1.加载MyBatis配置文件
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.github.rolven95.database.model
    configuration:
#  　　# 开启驼峰uName自动映射到u_name
        map-underscore-to-camel-case: true

## 打印sql
#logging:
#  level:
#    ssm.app.mapper: debug